<a href="https://colab.research.google.com/github/rokmr/Kick-Start-AI/blob/main/src/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Arange & Linspace

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [5]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [6]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

# Slice

In [7]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0]

0

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Numpy fron List

In [17]:
my_list = [1,2,3]
my_array = np.array([1,2,3])
my_list, my_array

([1, 2, 3], array([1, 2, 3]))

In [18]:
type(my_list), type(my_array)

(list, numpy.ndarray)

In [19]:
np.array(my_list)

array([1, 2, 3])

In [20]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Zeros, Ones, Identity

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
def one_hot(labels, num_classes=None):
    if num_classes is None:
        num_classes = np.max(labels) + 1
    return np.eye(num_classes)[labels]

labels = [3, 5, 1 , 3, 2]
one_hot(labels)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

# Random Numpy Array

In [27]:
np.random.rand(2) #uniform distribution

array([0.8304733 , 0.94711711])

In [28]:
np.random.rand(5,5) #uniform distribution

array([[0.95567651, 0.13543743, 0.86261663, 0.58975566, 0.26033458],
       [0.09115418, 0.05327818, 0.16883285, 0.43745157, 0.189776  ],
       [0.90575932, 0.89403851, 0.40349739, 0.22715198, 0.37938942],
       [0.81873186, 0.14736106, 0.39178308, 0.51010857, 0.93387133],
       [0.48245742, 0.75646287, 0.12068549, 0.13098594, 0.91580054]])

In [29]:
np.random.randn(2) #normal distribution

array([ 0.45173461, -0.16427407])

In [30]:
np.random.randn(5,5) #normal distribution

array([[-2.95428137, -0.7111761 ,  1.38528046,  1.04585711,  0.97217051],
       [-0.47317333,  0.62933044, -1.56491275, -0.04031625, -0.64349906],
       [ 0.85819476, -0.06592148,  0.28690853, -0.86925575,  0.45145225],
       [ 0.14036792, -0.55987335,  0.15806937, -0.21274992,  2.59794101],
       [-0.76273037, -1.45420322, -0.29393502,  1.54188111, -0.51924988]])

In [31]:
np.random.randint(1,100)

58

In [32]:
np.random.randint(1,100,10)

array([60,  1, 54, 37,  3, 82,  7, 62, 21, 92])

In [33]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr = np.arange(25)
randarr = np.random.randint(0,50,10)
arr, randarr

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]),
 array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2]))

# Max, Min, Argmax & Argmin

In [35]:
randarr.max(), randarr.min(), randarr.argmax(), randarr.argmin()

(39, 2, 7, 9)

In [36]:
arr.shape

(25,)

# Reshape

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
arr.reshape(1,25).shape

(1, 25)

In [40]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [41]:
arr.reshape(25,1).shape

(25, 1)

# Data Type

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr.astype(np.int8).dtype

dtype('int8')

In [44]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# Matrix

In [45]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [46]:
arr_2d[1]

array([20, 25, 30])

In [47]:
arr_2d[1][0]

20

In [48]:
arr_2d[1,0]

20

In [49]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [50]:
arr_2d[2]

array([35, 40, 45])

In [51]:
arr_2d[2,:]

array([35, 40, 45])

# Operation

In [52]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Boolean Array

In [53]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [54]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [56]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Math Operations

In [58]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [61]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
arr/arr

/var/folders/xm/hv0x78kx5mvbzd2tsn4q98km0000gn/T/ipykernel_13302/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [63]:
1/arr

/var/folders/xm/hv0x78kx5mvbzd2tsn4q98km0000gn/T/ipykernel_13302/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [64]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [65]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [66]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [67]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [68]:
np.log(arr)

/var/folders/xm/hv0x78kx5mvbzd2tsn4q98km0000gn/T/ipykernel_13302/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [69]:
arr = np.arange(0,10)


In [70]:
arr.min(), arr.max(), arr.mean()

(0, 9, 4.5)

In [71]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [73]:
arr_2d.sum(axis=1)

array([10, 26, 42])

## Stack

In [74]:
arr = np.arange(1, 11)
arr, arr.shape

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), (10,))

In [75]:
stack_0 = np.stack([arr, arr], axis=0)
stack_0, stack_0.shape

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 (2, 10))

In [76]:
stack_1 = np.stack([arr, arr], axis=1)
stack_1, stack_1.shape

(array([[ 1,  1],
        [ 2,  2],
        [ 3,  3],
        [ 4,  4],
        [ 5,  5],
        [ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [ 9,  9],
        [10, 10]]),
 (10, 2))

# Misc

In [77]:
x = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])

pad_top = 1
pad_bottom = 1
pad_left = 2
pad_right = 2

padded = np.pad(x, 
                ((0, 0),           # No padding for batch dimension
                 (pad_top, pad_bottom),    # Padding for height
                 (pad_left, pad_right)),   # Padding for width
                mode='constant')

print("Original shape:", x.shape)
print("Padded shape:", padded.shape)

print("\nOriginal array:")
print(x[0])  # Show first batch

print("\nPadded array:")
print(padded[0])  # Show first batch

Original shape: (1, 3, 3)
Padded shape: (1, 5, 7)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Padded array:
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 7 8 9 0 0]
 [0 0 0 0 0 0 0]]
