<a href="https://colab.research.google.com/github/rokmr/Kick-Start-AI/blob/main/src/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.6.0+cu124'

# Scalar

In [ ]:
scalar_tensor = torch.tensor(7)
scalar_tensor

tensor(7)

In [ ]:
scalar_Tensor = torch.Tensor(7)
scalar_Tensor

tensor([ 3.9236e-43,  0.0000e+00, -1.4002e+23,  4.4385e-41,  0.0000e+00,
         0.0000e+00,  0.0000e+00])

In [ ]:
print(f"scalar_tensor.ndim : {scalar_tensor.ndim}, scalar_Tensor.ndim : {scalar_Tensor.ndim}")

scalar_tensor.ndim : 0, scalar_Tensor.ndim : 1


In [ ]:
print(f"{scalar_tensor.item()} ||  {scalar_Tensor}")

7 ||  tensor([ 3.9236e-43,  0.0000e+00, -1.4002e+23,  4.4385e-41,  0.0000e+00,
         0.0000e+00,  0.0000e+00])


In [ ]:
print(f"{scalar_tensor.shape} ||  {scalar_Tensor.shape}")

torch.Size([]) ||  torch.Size([7])


# Vector

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

# Matrix

In [ ]:
matrix = torch.tensor([[1, 2],
                       [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

# Tensor

In [ ]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor.dtype

torch.int64

## Random Tesnor

In [ ]:
random_img_tensor = torch.rand(size=(224, 224, 3))
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_img_tensor.dtype

torch.float32

## Zeros

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.shape, zeros.ndim

(torch.Size([3, 4]), 2)

In [ ]:
zeros.dtype

torch.float32

## Ones

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.shape, ones.ndim

(torch.Size([3, 4]), 2)

In [ ]:
ones.dtype

torch.float32

## Zeros and Ones like

In [ ]:
five_to_ten = torch.arange(5,11, 1)
five_to_ten

tensor([ 5,  6,  7,  8,  9, 10])

In [ ]:
zeros_like = torch.zeros_like(five_to_ten)
zeros_like

tensor([0, 0, 0, 0, 0, 0])

In [ ]:
zeros_like.shape, zeros_like.ndim

(torch.Size([6]), 1, 6)

In [ ]:
ones_like = torch.ones_like(five_to_ten)
ones_like

tensor([1, 1, 1, 1, 1, 1])

In [ ]:
ones_like.shape, ones_like.ndim

(torch.Size([6]), 1)

## Specific datatype

In [ ]:
data1 = torch.tensor([1,2,3])
data1.dtype

torch.int64

In [ ]:
data1 = torch.tensor([1,2,3], dtype=torch.float16)
data1.dtype

torch.float16

In [ ]:
data1 = data1.type(torch.float32)
data1.dtype

torch.float32

# Operations

## Basics

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.multiply(tensor, tensor)

tensor([1, 4, 9])

In [ ]:
tensor * tensor # Dot-product

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## nn.Linear

In [ ]:
linear_layer = torch.nn.Linear(in_features=2,
                               out_features=6)

x1_input= torch.tensor([1,2], dtype=torch.float32)

x2_input = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)

x1_output = linear_layer(x1_input)
x2_output = linear_layer(x2_input)

x1_input.shape, x1_output.shape, x2_input.shape, x2_output.shape

(torch.Size([2]), torch.Size([6]), torch.Size([3, 2]), torch.Size([3, 6]))

## Min Max

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min(), x.max()

(tensor(0), tensor(90))

In [ ]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

# Reshaping, view, stacking, squeezing and unsqueezing

## Reshape

In [ ]:
x = torch.arange(0., 10.)
x.dtype

torch.float32

In [ ]:
x = torch.arange(0, 12)
x.dtype

torch.int64

In [ ]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x_reshaped = x.reshape(2,6)
x_reshaped

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [ ]:
x_reshaped = x.reshape(3,4)
x_reshaped

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
x_reshaped[0,0] = -111
x_reshaped

tensor([[-111,    1,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]])

In [ ]:
# .reshape may or may not share the underlying data

## View

In [ ]:
x = torch.arange(0., 12.)
x.dtype

torch.float32

In [ ]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
x_view = x.view(2,6)
x_view

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [ ]:
x_view[0,0] = -111
x_view

tensor([[-111.,    1.,    2.,    3.,    4.,    5.],
        [   6.,    7.,    8.,    9.,   10.,   11.]])

## Stack

In [ ]:
x = torch.arange(0,5)
x

tensor([0, 1, 2, 3, 4])

In [ ]:
x_dim0 = torch.stack([x,x,x,x], dim=0)
x_dim0.shape

torch.Size([4, 5])

In [ ]:
x_dim0 = torch.stack([x,x,x,x], dim=1)
x_dim0.shape

torch.Size([5, 4])

## Unsqueeze & Squeeze

In [ ]:
x.shape

torch.Size([5])

In [ ]:
x_unsqueeze0 = x.unsqueeze(dim=0)
x_unsqueeze0.shape

torch.Size([1, 5])

In [ ]:
x_unsqueeze1 = x.unsqueeze(dim=1)
x_unsqueeze1.shape

torch.Size([5, 1])

In [ ]:
x_squeeze0 = x_unsqueeze0.squeeze()
x_squeeze0.shape

torch.Size([5])

In [ ]:
x_squeeze1 = x_unsqueeze0.squeeze()
x_squeeze1.shape

torch.Size([5])

In [ ]:
x_unsqueeze02 = x_unsqueeze0.unsqueeze(dim=2)
x_unsqueeze02.shape

torch.Size([1, 5, 1])

In [ ]:
x_squeeze02 =x_unsqueeze02.squeeze()
x_squeeze02.shape

torch.Size([5])

In [ ]:
x_unsqueeze01 = x_unsqueeze0.unsqueeze(dim=1)
x_unsqueeze01.shape

torch.Size([1, 1, 5])

In [ ]:
x_squeeze01 =x_unsqueeze01.squeeze()
x_squeeze01.shape

torch.Size([5])

## Index

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][1]

tensor([4, 5, 6])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])